spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      enkey:
      auto-commit: true
      pool-size: 2
      max-life-time: 1800000
      idle-timeout: 30000
      leak-detection-threshold: 30000
      validation-timeout: 1500
